/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3d/Bee_Xmas.glb')
  const { actions } = useAnimations(animations, group)
  console.log('actions', actions);
  useEffect(() => {
    actions["Bee_Rig:SHJntGrp|Take 001|BaseLayer"].play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.Bee_RigTrajectorySHJnt} />
        <skinnedMesh
          geometry={nodes.Mesh003.geometry}
          material={materials['Bee_Rig:lambert4']}
          skeleton={nodes.Mesh003.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh003_1.geometry}
          material={nodes.Mesh003_1.material}
          skeleton={nodes.Mesh003_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh003_2.geometry}
          material={materials['Bee_Rig:lambert2']}
          skeleton={nodes.Mesh003_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh002.geometry}
          material={nodes.Mesh002.material}
          skeleton={nodes.Mesh002.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh002_1.geometry}
          material={nodes.Mesh002_1.material}
          skeleton={nodes.Mesh002_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Bee_RigMouth_MSH.geometry}
          material={nodes.Bee_RigMouth_MSH.material}
          skeleton={nodes.Bee_RigMouth_MSH.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh001.geometry}
          material={nodes.Mesh001.material}
          skeleton={nodes.Mesh001.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh001_1.geometry}
          material={nodes.Mesh001_1.material}
          skeleton={nodes.Mesh001_1.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/Bee_Xmas.glb')
