import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/3d/Billy.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="defaultScene">
        <group position={[-357.7, -0.1, -182.1]}>
          <mesh
            name="mesh_0"
            castShadow
            receiveShadow
            geometry={nodes.mesh_0.geometry}
            material={nodes.mesh_0.material}
          />
          <mesh
            name="mesh_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh_1.geometry}
            material={nodes.mesh_1.material}
          />
          <mesh
            name="mesh_13"
            castShadow
            receiveShadow
            geometry={nodes.mesh_13.geometry}
            material={nodes.mesh_13.material}
          />
          <mesh
            name="mesh_17"
            castShadow
            receiveShadow
            geometry={nodes.mesh_17.geometry}
            material={nodes.mesh_17.material}
          />
          <mesh
            name="mesh_11"
            castShadow
            receiveShadow
            geometry={nodes.mesh_11.geometry}
            material={nodes.mesh_11.material}
          />
          <mesh
            name="mesh_12"
            castShadow
            receiveShadow
            geometry={nodes.mesh_12.geometry}
            material={nodes.mesh_12.material}
          />
          <mesh
            name="mesh_2"
            castShadow
            receiveShadow
            geometry={nodes.mesh_2.geometry}
            material={nodes.mesh_2.material}
          />
          <mesh
            name="mesh_3"
            castShadow
            receiveShadow
            geometry={nodes.mesh_3.geometry}
            material={nodes.mesh_3.material}
          />
          <mesh
            name="mesh_7"
            castShadow
            receiveShadow
            geometry={nodes.mesh_7.geometry}
            material={nodes.mesh_7.material}
          />
          <mesh
            name="mesh_4"
            castShadow
            receiveShadow
            geometry={nodes.mesh_4.geometry}
            material={nodes.mesh_4.material}
          />
          <mesh
            name="mesh_5"
            castShadow
            receiveShadow
            geometry={nodes.mesh_5.geometry}
            material={nodes.mesh_5.material}
          />
          <mesh
            name="mesh_8"
            castShadow
            receiveShadow
            geometry={nodes.mesh_8.geometry}
            material={nodes.mesh_8.material}
          />
          <mesh
            name="mesh_9"
            castShadow
            receiveShadow
            geometry={nodes.mesh_9.geometry}
            material={nodes.mesh_9.material}
          />
          <mesh
            name="mesh_10"
            castShadow
            receiveShadow
            geometry={nodes.mesh_10.geometry}
            material={nodes.mesh_10.material}
          />
          <mesh
            name="mesh_14"
            castShadow
            receiveShadow
            geometry={nodes.mesh_14.geometry}
            material={nodes.mesh_14.material}
          />
          <mesh
            name="mesh_15"
            castShadow
            receiveShadow
            geometry={nodes.mesh_15.geometry}
            material={nodes.mesh_15.material}
          />
          <mesh
            name="mesh_16"
            castShadow
            receiveShadow
            geometry={nodes.mesh_16.geometry}
            material={nodes.mesh_16.material}
          />
          <mesh
            name="mesh_18"
            castShadow
            receiveShadow
            geometry={nodes.mesh_18.geometry}
            material={nodes.mesh_18.material}
          />
          <mesh
            name="mesh_6"
            castShadow
            receiveShadow
            geometry={nodes.mesh_6.geometry}
            material={nodes.mesh_6.material}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d/Billy.glb')