/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/BILLY_XMAS.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[0, 0.07, 0]} rotation={[-2.96, 0, -Math.PI / 2]} scale={0.01} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.Root_M_New1} />
        <skinnedMesh
          geometry={nodes.model22.geometry}
          material={nodes.model22.material}
          skeleton={nodes.model22.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model23.geometry}
          material={nodes.model23.material}
          skeleton={nodes.model23.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model24.geometry}
          material={nodes.model24.material}
          skeleton={nodes.model24.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model25.geometry}
          material={nodes.model25.material}
          skeleton={nodes.model25.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model26.geometry}
          material={nodes.model26.material}
          skeleton={nodes.model26.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model27.geometry}
          material={nodes.model27.material}
          skeleton={nodes.model27.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model28.geometry}
          material={nodes.model28.material}
          skeleton={nodes.model28.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model29.geometry}
          material={nodes.model29.material}
          skeleton={nodes.model29.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model30.geometry}
          material={nodes.model30.material}
          skeleton={nodes.model30.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model31.geometry}
          material={nodes.model31.material}
          skeleton={nodes.model31.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model32.geometry}
          material={nodes.model32.material}
          skeleton={nodes.model32.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model33.geometry}
          material={nodes.model33.material}
          skeleton={nodes.model33.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model34.geometry}
          material={nodes.model34.material}
          skeleton={nodes.model34.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model36.geometry}
          material={nodes.model36.material}
          skeleton={nodes.model36.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model37.geometry}
          material={nodes.model37.material}
          skeleton={nodes.model37.skeleton}
        />
        <skinnedMesh
          geometry={nodes.model38.geometry}
          material={nodes.model38.material}
          skeleton={nodes.model38.skeleton}
        />
        <skinnedMesh geometry={nodes.model41.geometry} material={materials.phong2} skeleton={nodes.model41.skeleton} />
        <skinnedMesh geometry={nodes.model42.geometry} material={materials.phong5} skeleton={nodes.model42.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/BILLY_XMAS.glb')
