/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3d/Sunny_dance_Xmas.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions["Armature|Take 001|BaseLayer"].play();
    // actions["L_HAND|Take 001|BaseLayer"].play();
    // actions["R_HAND|Take 001|BaseLayer"].play();
  });
  console.log(actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[-0.42, 0.06, 0.34]} rotation={[0, -0.02, 0.01]} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.Root} />
        <skinnedMesh
          geometry={nodes.GEO_HAIR1.geometry}
          material={nodes.GEO_HAIR1.material}
          skeleton={nodes.GEO_HAIR1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_L_EYEBROW.geometry}
          material={nodes.GEO_L_EYEBROW.material}
          skeleton={nodes.GEO_L_EYEBROW.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh014.geometry}
          material={nodes.Mesh014.material}
          skeleton={nodes.Mesh014.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh014_1.geometry}
          material={nodes.Mesh014_1.material}
          skeleton={nodes.Mesh014_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_LEFT_BOOT.geometry}
          material={nodes.GEO_LEFT_BOOT.material}
          skeleton={nodes.GEO_LEFT_BOOT.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_LEFT_EYE.geometry}
          material={nodes.GEO_LEFT_EYE.material}
          skeleton={nodes.GEO_LEFT_EYE.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_LEFT_EYELASH.geometry}
          material={nodes.GEO_LEFT_EYELASH.material}
          skeleton={nodes.GEO_LEFT_EYELASH.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_LEFT_GLOVE.geometry}
          material={nodes.GEO_LEFT_GLOVE.material}
          skeleton={nodes.GEO_LEFT_GLOVE.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_PANTS.geometry}
          material={nodes.GEO_PANTS.material}
          skeleton={nodes.GEO_PANTS.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_R_EYEBROW.geometry}
          material={nodes.GEO_R_EYEBROW.material}
          skeleton={nodes.GEO_R_EYEBROW.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_RIGHT_BOOT.geometry}
          material={nodes.GEO_RIGHT_BOOT.material}
          skeleton={nodes.GEO_RIGHT_BOOT.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_RIGHT_EYE001.geometry}
          material={nodes.GEO_RIGHT_EYE001.material}
          skeleton={nodes.GEO_RIGHT_EYE001.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_RIGHT_EYELASHES.geometry}
          material={nodes.GEO_RIGHT_EYELASHES.material}
          skeleton={nodes.GEO_RIGHT_EYELASHES.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_RIGHT_GLOVE.geometry}
          material={nodes.GEO_RIGHT_GLOVE.material}
          skeleton={nodes.GEO_RIGHT_GLOVE.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_SWEATER.geometry}
          material={nodes.GEO_SWEATER.material}
          skeleton={nodes.GEO_SWEATER.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_TEETH.geometry}
          material={nodes.GEO_TEETH.material}
          skeleton={nodes.GEO_TEETH.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEO_TONGUE.geometry}
          material={nodes.GEO_TONGUE.material}
          skeleton={nodes.GEO_TONGUE.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GEOHEAD.geometry}
          material={materials.lambert2}
          skeleton={nodes.GEOHEAD.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh015.geometry}
          material={nodes.Mesh015.material}
          skeleton={nodes.Mesh015.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh015_1.geometry}
          material={nodes.Mesh015_1.material}
          skeleton={nodes.Mesh015_1.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/Sunny_dance_Xmas.glb')
